services:
  desperfectosweb-front:
    container_name: desperfectosweb-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - API_URL=http://desperfectosweb-back:8080
    networks:
      - default
